language: php
os: linux
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before-install:
  - sudo apt-get -y install sshpass

before_script:
  - pear install soap-beta
  - mv test_env/test_conf.php conf/conf.php

script:
  - find . -name "*.php" -exec php -l {} \;
  - php -f "index.php" > /dev/null

after_success:
  - grep "VERSION" core/core.php | cut -d"'" -f2 > version.file
  - zip -r mantis-reporter-`cat version.file`.zip * -x "*/\." -x "test_env/*" -x "CODE_OF_CONDUCT.md" -x "*_secret.php" -x "version.file"
  - sshpass -p ${SFTP_PASSWORD} scp -o StrictHostKeyChecking=no mantis-reporter-`cat version.file`.zip ${SFTP_USER}@${SFTP_SERVER}:${SFTP_PATH}
  - rm -f mantis-reporter-`cat version.file`.zip
  - rm -f version.file
