language: php
os: linux
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - pear install soap-beta
  - mv test_env/test_conf.php conf/conf.php


script:
  - find . -name "*.php" -exec php -l {} \;
  - php -f "index.php" > /dev/null

after_success:
  - bash ./test_env/pack_release.sh
  - curl -T *.zip ftp://${SFTP_USER}:${SFTP_PASSWORD}:${SFTP_SERVER}/
  - rm -f *.zip
